# fly.toml file generated for galley on 2022-06-11T09:09:07-04:00

app = "galley"

kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

# we don't use the release command:
# see: https://gist.github.com/Copser/af3bf28cf9ae4f42a358d7d0a19f8b5e#problem-2-release_command
# [deploy]
  # release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "galley.fly.dev"
  PORT = "8080"
  DATABASE_PATH = "/data/galleydata_prod.db"
  GALLEY_S3_BUCKET_DEV = "theiceshelf-galley-dev"
  GALLEY_S3_BUCKET_PROD = "theiceshelf-galley"

[mounts]
source = "galley_data"
destination = "/data"


[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
